[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "1272231bef1b3bb104d18f692596e96b3fe9b52b"
os = "macos"

    [[Cairo.download]]
    sha256 = "57fb03951a5612fa6a58572f01080ac440f95b297b7a1ccf35755d7435d94882"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.aarch64-apple-darwin.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "d7f52a3c9c7d515120c12ffdb1ef4763c53cd28f"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "3a4a9adb63d06999ed96d0c5b1e21986ceaf0ffb7ffc0e62ecfd62ca01109fc3"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.aarch64-linux-gnu.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "e6168f7f47dce314660d31ff53d04d6606e25ed9"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "d7bb2427a218c53dc4949721b3ecbb5027f2eab9bb4bb00676187bf40d95c937"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.aarch64-linux-musl.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "15ce4b109df9ce89520d036e273f4d5ca40b2a55"
os = "freebsd"

    [[Cairo.download]]
    sha256 = "1cfb176008ac6c9cc4274328e8059a3ff54ad4c30e269a3c5848768c6edb1ddc"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.aarch64-unknown-freebsd.tar.gz"
[[Cairo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e533dabcd49ad71b3dc7537a42f374a7aae6ac4"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "8c4f23e7cd53905db72423aba24dc238ad07455fd3afd6e034e2a93ca1b98f60"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.armv6l-linux-gnueabihf.tar.gz"
[[Cairo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22b61b48b7954071bb7dac4deb782094a37fbb59"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "b3353526701f7e6c09730685a70a450921b3037191a83759743cdddd61c873b6"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.armv6l-linux-musleabihf.tar.gz"
[[Cairo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67c907a7fa3d39e378d0b877afb00a055ed0e992"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "cb526b863ed4c63a674cacc6cf14fc21d17c0620c6ccee02b724c444ab41172f"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.armv7l-linux-gnueabihf.tar.gz"
[[Cairo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0425bceb1c6799aee41f193cc6b82411f632cd5a"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "581bbb1c3d4d818060d68178995df8be51f17a8f399bb961e584451a29174ea3"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.armv7l-linux-musleabihf.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "61cde80f6a954c3a4d1a528fd9fc6baf3e622389"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "e91f59d602cbfc88e76bc79fbdec00efc9e01d49fa5253b6b2f212186d179ddb"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.i686-linux-gnu.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "0082753c3d7d43555c891d5c5985b2ce06ecc023"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "6d960e00e39a39a5d6c0a409b396dc3002654b7f4e0c91f4f7549c58c3bbde39"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.i686-linux-musl.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "d5838f60f9cd49917f7e02bb46a043b60264d8c7"
os = "windows"

    [[Cairo.download]]
    sha256 = "0451f38e2cef3a1184a31c8bbb93e574653c1599803c1cf53a6c70d96329a559"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.i686-w64-mingw32.tar.gz"
[[Cairo]]
arch = "powerpc64le"
git-tree-sha1 = "00c8762aca2b3a8fa851afdbd4a437b4854a1002"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "237a5b1f4369c5e12f3c8c653cc8929f407a80d0c0fc550be415845589b3bfa1"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.powerpc64le-linux-gnu.tar.gz"
[[Cairo]]
arch = "riscv64"
git-tree-sha1 = "f89edac6b59aabbbbecc82ce4c3ac38b7ae0f2a2"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "8e2a57468dcd2c54253837de8192c446c177e915c1bf744b2a2f431745122fff"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.riscv64-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "18bfdff90c23c3f68cdb79bf5f92e84ec9178c8f"
os = "macos"

    [[Cairo.download]]
    sha256 = "17b1933a001017db60d93b540490d7ec0b57ddb0fc6ef6b3be4f42ad6f5c5a14"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.x86_64-apple-darwin.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "ae5d4078c8d35999915cd399e74ece39c1f2ad41"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "1b09f3f8926f055791a8f741eae8323565fbb5fd715a283ec67e44646e4e7582"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.x86_64-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "9aaf9a1439e0dc831679ade23c42426a6a5aea66"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "abc7bac09a95be8a454a5b030a8967c30017c92c3d2807d7315de87b9db60fff"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.x86_64-linux-musl.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "0e8f5102c268bf86d0ecdf7a1a5a234cca3ccd09"
os = "freebsd"

    [[Cairo.download]]
    sha256 = "a54b6aea3e94fa0bab29a6b962ac844dbb1f0935202f9c8f78c2765a5cb132a7"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.x86_64-unknown-freebsd.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "e69be2a7cafa348164bf75e6734827c27cb15cbc"
os = "windows"

    [[Cairo.download]]
    sha256 = "bf8427fdfb6900b6ccea991eaaab7877079d6822a79b8bc147ea2230c12949be"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.18.6+0/Cairo.v1.18.6.x86_64-w64-mingw32.tar.gz"
